// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfnengizqdnpkjxbwyvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmbmVuZ2l6cWRucGtqeGJ3eXZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MDIzNDcsImV4cCI6MjA1ODQ3ODM0N30.WrW0gj40G4D9H7ayugJGCqnAOE688Q51fggiPADXHAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);